version: '3.8'

services:
  db:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=seu_usuario
      - POSTGRES_PASSWORD=sua_senha
      - POSTGRES_DB=gestao_academica_db
    ports:
      - '5432:5432'
    volumes:
      - db_data:/var/lib/postgresql/data

  app:
    build: .
    restart: always
    ports:
      - '8080:8080'
    environment:
      - spring.datasource.url=jdbc:postgresql://db:5432/gestao_academica_db
      - spring.datasource.username=seu_usuario
      - spring.datasource.password=sua_senha
    depends_on:
      - db

volumes:
  db_data: